### ISSUE TITLE
pin issue

### ISSUE THREAD

**Issue by sniperxnl** [spigotx/Moodlite#1]
Hai guys, i get this message

In file included from C:\Users\Bas\Downloads\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:12:0:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.001

 #    pragma message "FastLED version 3.002.001"

                     ^

In file included from C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:65:0,

                 from C:\Users\Bas\Downloads\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:12:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:48:0,

                 from C:\Users\Bas\Downloads\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:12:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/fastpin.h: In instantiation of 'class FastPin<6u>':

C:\Program Files (x86)\Arduino\libraries\FastLED-master/platforms/esp/8266/clockless_esp8266.h:21:49:   required from 'class ClocklessController<6, 20, 50, 30, (EOrder)66u, 0, false, 50>'

C:\Program Files (x86)\Arduino\libraries\FastLED-master/chipsets.h:538:7:   required from 'class WS2812Controller800Khz<6u, (EOrder)66u>'

C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:104:52:   required from 'class WS2812B<6u, (EOrder)66u>'

C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:299:39:   required from 'static CLEDController& CFastLED::addLeds(CRGB*, int, int) [with CHIPSET = WS2812B; unsigned char DATA_PIN = 6u; EOrder RGB_ORDER = (EOrder)66u]'

C:\Users\Bas\Downloads\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:93:69:   required from here

C:\Program Files (x86)\Arduino\libraries\FastLED-master/fastpin.h:207:2: error: static assertion failed: Invalid pin specified

  static_assert(validpin(), "Invalid pin specified");

  ^

exit status 1
Fout bij het compileren voor board Generic ESP8266 Module

**Comment by spigotx** [comment]
Which ESP device do you use? PIN 6 is for NodeMCU device. If you are using Wemos D1 mini or other device you have to change the PIN number.

**Comment by sniperxnl** [comment]
Geekcreit® LoLin V3 NodeMcu Lua WIFI-ontwikkelingskaart ESP8266 Seriële wifi-module
https://banggood.app.link/HpiGfpZ77S

I have this one

**Comment by sniperxnl** [comment]
It works now

**Comment by sniperxnl** [comment]
Hai Guys,

I have just downloaded your lasted version and i get again the same fastled pin issue. 
The old version i can upload it without problems


C:\Program Files (x86)\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

**Comment by spigotx** [comment]
`C:\Program Files (x86)\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined. All SPI access will default to bitbanged output
pragma message "No hardware SPI pins defined. All SPI access will default to bitbanged output"`

This is not an error. It's just warning, which is normal for FastLED.

If you mean LED pin, check LED_PIN declaration it must correspond to your ESP
