### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by sniperxnl** [spigotx/Moodlite#20]
Guys i get this all the time

C:\Users\Bas\Documents\Programs\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino: In member function 'String& ByteString::copy(const void*, unsigned int)':

Moodlite:419:4: error: expected primary-expression before ')' token

   ()len = length;

    ^

Moodlite:419:5: error: expected ';' before 'len'

   ()len = length;

     ^

Moodlite:420:30: error: cannot convert 'String::buffer' from type 'const char* (String::)()const' to type 'void*'

   memcpy(buffer, data, length);

                              ^

Moodlite:421:16: error: invalid types '<unresolved overloaded function type>[unsigned int]' for array subscript

   buffer[length] = 0;

                ^

exit status 1
expected primary-expression before ')' token

**Comment by sniperxnl** [comment]
Arduino:1.8.8 (Windows 8.1), Board:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:1MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

WAARSCHUWING: bibliotheek Timezone-master beweert te werken onder architectuur (avr) en kan incompatible zijn met uw huidige board dat werkt onder architectuur (esp8266).
In file included from C:\Users\Bas\Documents\Programs\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:31:0:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.004

 #    pragma message "FastLED version 3.002.004"

                     ^

In file included from C:\Program Files (x86)\Arduino\libraries\FastLED-master/led_sysdefs.h:27:0,

                 from C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:41,

                 from C:\Users\Bas\Documents\Programs\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:31:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/platforms/esp/8266/led_sysdefs_esp8266.h:15:17: error: conflicting declaration 'typedef uint8_t boolean'

 typedef uint8_t boolean;

                 ^

In file included from sketch\Moodlite.ino.cpp:1:0:

C:\Users\Bas\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266/Arduino.h:170:14: error: 'boolean' has a previous declaration as 'typedef bool boolean'

 typedef bool boolean;

              ^

In file included from C:\Program Files (x86)\Arduino\libraries\FastLED-master/FastLED.h:65:0,

                 from C:\Users\Bas\Documents\Programs\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino:31:

C:\Program Files (x86)\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Users\Bas\Documents\Programs\Moodlite-master\Moodlite-master\Arduino\Moodlite\Moodlite.ino: In member function 'String& ByteString::copy(const void*, unsigned int)':

Moodlite:419:4: error: expected primary-expression before ')' token

   ()len = length;

    ^

Moodlite:419:5: error: expected ';' before 'len'

   ()len = length;

     ^

Moodlite:420:30: error: cannot convert 'String::buffer' from type 'const char* (String::)()const' to type 'void*'

   memcpy(buffer, data, length);

                              ^

Moodlite:421:16: error: invalid types '<unresolved overloaded function type>[unsigned int]' for array subscript

   buffer[length] = 0;

                ^

exit status 1
expected primary-expression before ')' token

Dit rapport zou meer informatie bevatten met
"Uitgebreide uitvoer weergeven tijden compilatie"
optie aan in Bestand -> Voorkeuren.

**Comment by HELEMAALNIKS** [comment]
I have the same problem...

**Comment by spigotx** [comment]
Removed obsolete code. It should compile fine now.
