### ISSUE TITLE
Suggestion: Support for OpenMQTTGateway

### ISSUE THREAD

**Issue by chrisfu** [spigotx/Moodlite#4]
I've yet to assemble my BOM to commence my own build, but hope to get started in then next week or two. Never the less, I spy an opportunity to integrate this project with the great OpenMQTTGateway project.

I propose that this issue is used to discuss the feasibility of such a task. Once I'm hands-on with the project I'll be happy to contribute to any community effort.

Hopefully there is some interest in helping to achieve this. After all, automation is great. :)

Reference: https://github.com/1technophile/OpenMQTTGateway

**Comment by chrisfu** [comment]
I've come across [CoogleIOT](https://github.com/ThisSmartHouse/CoogleIOT) that would provide the Wifi Manager aspect of #3 as well as the OpenMQTT support of this issue.

**Comment by spigotx** [comment]
Hi chrisfu.
Thanks for the suggestions.
Wifi manager is already included since v1.1. 
MQTT is a good idea, but first I have to establish basic working version and than we can start adding more features.
